### PR TITLE
KlerosGovernor + yarn.lock update

### PR DESCRIPTION
**Pull request by unknownunknown1**

### CODE REVIEW

**Comment by unknownunknown1** [comment]
At this point I think it's easier to just add library directly to the contract

**Comment by epiqueras** [comment]
This isn't even compiling locally because you have duplicated imports. Have you tried it?

Here, I fixed it and pushed it for you: https://github.com/kleros/kleros/commit/5826460269a23bd317f470103a29b524444ce5e4

**Comment by unknownunknown1** [comment]
Thanks, no I haven't tried it

**Comment by epiqueras** [comment]
No problem, but in the future, please test things locally before pushing.

**Pull request closed without merging**
