### PR TITLE
feat(KlerosGovernor): created a governor contract for KlerosLiquid

### PR DESCRIPTION
**Pull request by unknownunknown1**

### CODE REVIEW

**Comment by unknownunknown1** [comment]
Fixed, I think

**Comment by epiqueras** [comment]
`Error: Could not find kleros-interaction/contracts/libraries/CappedMath.sol from any sources;`

I think you need to update `kleros-interaction`.

**Comment by unknownunknown1** [comment]
My remote repo you mean?
I have this file there https://github.com/unknownunknown1/kleros-interaction/tree/master/contracts/libraries

**Comment by epiqueras** [comment]
No, the dependency of this repo.

**Comment by unknownunknown1** [comment]
What's the way to do that? I'm kinda lost

**Comment by epiqueras** [comment]
https://yarnpkg.com/lang/en/docs/cli/upgrade

**Comment by unknownunknown1** [comment]
Ran the command. Now I need to push yarn.lock?

**Comment by epiqueras** [comment]
Yes.

**Comment by unknownunknown1** [comment]
Just in case:  I was getting some errors upon committing, had to add "--no-verify".

**Comment by epiqueras** [comment]
The NPM distribution was outdated. I just deployed a new version. Upgrade it again please.

**Comment by unknownunknown1** [comment]
I ran "yarn upgrade" but it didn't change yarn.lock file from the one I committed earlier

**Comment by epiqueras** [comment]
It's `yarn upgrade @kleros/kleros-interaction`.

**Comment by unknownunknown1** [comment]
Same result

**Comment by epiqueras** [comment]
Try `yarn add @kleros/kleros-interaction`.

**Comment by unknownunknown1** [comment]
Error again. Maybe link to the file should be different?

**Comment by epiqueras** [comment]
It's `@kleros/kleros-interaction/...`.

Also, don't add `yarn` as an npm dependency and don't use `package-lock.json` , using multiple dependency managers can break things.

**Pull request closed without merging**
