### PR TITLE
Migrate Pinakion to MiniMeToken

### LINKED ISSUE #9: Use MinimeERC20 to prepare for voting
For the PNK contract:
https://github.com/kleros/kleros/blob/master/contracts/PinakionPOC.sol

MinimeERC20:
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableTokens/MiniMeTokenERC20.sol

### PR DESCRIPTION
**Pull request by kdembler**
Summary of changes:
- Migrate Pinakion to `MiniMeTokenERC20`
- Add implementations of `ApproveAndCallFallBack` and `TokenController` to `KlerosPOC` for it to be able to act as call back from `approveAndCall` and to act as a `MiniMeToken` controller respectively
- Update tests
- Remove `zeppelin-solidity` from dependencies

#### Note
Tests in this PR will not work until new version of `kleros-interaction` is released in NPM which contains changes from kleros/kleros-interaction#26.

Resolves #9

### CODE REVIEW

**Comment by clesaege** [comment]
Thanks for the work. Why would the kleros contract be the controller of the token?
I think we'll need a Kleros governance contract to be the controller of the token. What do you think?

**Comment by clesaege** [comment]
Yeah, you right, this was made a long time ago. We'll need to switch it to a governance contract in the future. I wonder if we could get some stuff from Aragon for the governance contract (they plan to make liquid voting smart contracts).

**Comment by clesaege** [comment]
Ok for the changes. But some conflicts need to be solved before merging.

**Comment by kdembler** [comment]
@clesaege Resolved conflicts.

**Pull request merged**
