### PR TITLE
Matts review of Kleros Governor

### PR DESCRIPTION
**Pull request by mtsalenc**
Currently, it is the responsability of the governor to ensure that `submissionDeposit` is higher than the arbitration cost. I believe this is not optimal, since it requires updating `submissionDeposit` any time the arbitration cost increases above it. Seems like people could forget about this.

Instead, I propose we update the `submitList` function to accept any amount greater than `submissionDeposit + arbitrationCost` and reimburse unused funds.

### CODE REVIEW

**Comment by unknownunknown1** [comment]
There is a problem that the function can't have any more variable because of "stack too deep" error. I had to remove some
https://github.com/kleros/kleros/commit/843a038fc88c6de1b053b99530d1749657f756e9#diff-9e5aa9100bdd1641897ccfd994013728

**Comment by unknownunknown1** [comment]
"The number of ongoing session or the maximum unsined integer if no sessions were ever submitted."

There is a typo. And by default session number is 0, because we create the first one upon deploying :)

**Comment by unknownunknown1** [comment]
"The number of ongoing sessions" - I think it should be just "session" not "sessions"

**Comment by mtsalenc** [comment]
Right. It's missing a "the" also. Adding it.

**Comment by mtsalenc** [comment]
On the matter of the stack limit error, here I think it is worth it to tradeoff readability to fix this. 

One way to do it is to use an array of 3 elements for the 3 hashes instead of 3 variables and replace where they are used.

It would look something like this:
```
function submitList(...) ... {
        ...  
        uint arbitrationCost = arbitrator.arbitrationCost(arbitratorExtraData);
        require(msg.value == submissionDeposit + arbitrationCost, "Submission deposit must be paid in exact amount.");
        ...
        // Using an array to get around the stack limit.
        // 0 - List hash.
        // 1 - Previous transaction hash.
        // 2 - Current transaction hash.
        bytes32[3] memory hashes;
        uint readingPosition;
        for (uint i = 0; i < _target.length; i++){
            bytes memory readData = new bytes(_dataSize[i]);
            Transaction storage transaction = submission.txs[submission.txs.length++];
            transaction.target = _target[i];
            transaction.value = _value[i];
            for (uint j = 0; j < _dataSize[i]; j++){
                readData[j] = _data[readingPosition + j];
            }
            transaction.data = readData;
            readingPosition += _dataSize[i];
            hashes[2] = keccak256(abi.encodePacked(transaction.target, transaction.value, transaction.data));
            require(uint(hashes[2]) >= uint(hashes[1]), "The transactions are in incorrect order.");
            hashes[0] = keccak256(abi.encodePacked(hashes[2], hashes[0]));
            hashes[1] = hashes[2];
        }
        require(!session.alreadySubmitted[hashes[0]], "The same list was already submitted earlier.");
        session.alreadySubmitted[hashes[0]] = true;
        submission.listHash = hashes[0];
        submission.submissionTime = now;
        session.sumDeposit += submissionDeposit + arbitrationCost;
        session.submittedLists.push(submissions.length - 1);
        emit ListSubmitted(submissions.length - 1, msg.sender, sessions.length - 1, _description);

        reservedETH += submissionDeposit + arbitrationCost;
    }
```

What do you think, @clesaege ?

**Pull request merged**
